name: 'Allure Report with history per branch'
description: 'Generate Allure Report with history per branch'
author: 'mgrybyk'
branding:
  icon: 'monitor'
  color: 'gray-dark'
inputs:
  prev_git_hash:
    description: 'Previous git commit hash'
    required: true
    default: ''
  results_dir:
    description: 'Input allure results dir, default "allure-results"'
    required: true
    default: 'allure-results'
  report_type:
    description: 'Output allure report dir, default "allure-report"'
    required: true
    default: 'allure-report'
  gh_pages_path:
    description: 'Folder path where the GitHub Pages files are checked out'
    required: true
    default: 'gh-pages'
  gh_pages_url:
    description: 'Base GitHub Pages URL where reports will be published'
    required: false
    default: 'https://potential-adventure-ozr3k39.pages.github.io'
  max_reports:
    description: 'Max active reports to keep per test type. Set to 0 to disable cleanup.'
    required: false
    default: 20
outputs:
  report_url:
    description: 'Published Allure Report url'
  test_result:
    description: 'test result: PASS | FAIL | UNKNOWN'
  test_result_icon:
    description: 'test result icon: ✅ | ❌ | ❔'
  test_result_passed:
    description: 'Number of passed tests'
  test_result_failed:
    description: 'Number of failed tests'
  test_result_total:
    description: 'Number of tests in total'
  report_generation_id:
    description: 'Name of the folder containing the generated Allure Report'
  report_path:
    description: 'Path to the folder containing the generated Allure Report relative to the repo root'
runs:
  using: 'docker'
  image: 'Dockerfile'
